### ISSUE TITLE
pos_item_sets and neg_item_sets generation？

### ISSUE THREAD

**Issue by chaoyushi** [l-lyl/DPPLikelihoods4SeqRec#1]
Hello, may I ask you some questions
How do you generate the pos_item_sets and neg_item_sets files you used in data_process/3_item_dpp_emb.py? 
Could you share the generated code?
I didn't find a rule of generation for the following examples:
train file
0 1420 1674 1786 777 1907 1366 2376 2428 2568 2572 2403 2656 2817 2830 2796 2854 2322 3042 3026 3032 3064
pos file
0;3026,1420,3042,2796,2428;1786,2403,2322,2572,2817;2568,2830,2854,1674,777;2817,2656,3032,1907,1366;3042,2376,2428,2796,3064
It seems that the following rules are not followed
"get sets from prepared sets files.
format:
       each line: u;id1,id2,...,id5;id2,id3,...,id6;...
 positive sets are selected from a user's interacted items (in training dataset), each set contains 5 items
 negative sets are randomly selected items that a user is not interested in"

**Comment by l-lyl** [comment]
You can find the corresponding rule in Section 2.2. 
Actually, it's a quite easy process, as you just need to select 5 positive items from observed historical interactions and 5 negative items each time. 
These items can be randomly selected or following a specific strategy. For instance, in our work we aim to make the positive subsets are diverse in category, so we just need to make sure the selected positive items have as many categories as possible. This is according to your needs.
